name: trial_cluestoday
description: Cross-platform Flutter app with navigation, bookmarking, and settings scaffolding.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  dio: ^5.4.0
  flutter_local_notifications: ^17.1.2
  firebase_core: ^2.25.4
  flutter_dotenv: ^5.1.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/config/.env
    - assets/config/.env.example
